target 'Taskon' do
  use_frameworks!
  
  pod 'Alamofire'
  pod 'CodableAlamofire'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'ReachabilitySwift'
  pod 'PromisedFuture'
  pod 'SkyFloatingLabelTextField'
  pod 'SwiftValidator'
  pod 'SnapKit'

end
