target 'Taskon' do
  use_frameworks!
  
  pod 'Alamofire'
  pod 'CodableAlamofire'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'ReachabilitySwift'
  pod 'PromisedFuture'
  pod 'SkyFloatingLabelTextField'
  pod 'SwiftValidator'
  pod 'SnapKit'
  pod 'SSSpinnerButton'
  pod 'JBDatePicker'
  pod 'SkeletonView'
  pod 'SimpleCheckbox'
  pod 'Loaf'
  pod 'Keyboard+LayoutGuide'
  pod 'ImageViewer'

end
